### ISSUE TITLE
hide-empty-dirs option breaks cache-dir option

### ISSUE THREAD

**Issue by allofmex** [mikeswain/cmdfs#1]
If option **hide-empty-dirs** is set, **cache directory** name **gets lost** after short time and cmdfs drops cache files in root dir (and in random subfolder like "?>?s??","`8?s??").
I tried some debugging on my own, the value of "options.cache_dir" gets lost after random period of time/files and is time and again overwritten by random data (Buffer-/Stack-Overflow??). If hide-empty-dirs is not set, no problems, cache file appear in set cachedir (tested on very large source dir).
(looks like problem appears only if function "static int is_empty(const char *dirpath)" gets used !?? )

Tested on two different Systems (both Ubuntu 17.04, tested inside docker container and on host itself, always same result)
cmdfs "/media/Storage/Backup/Photos 2005" /test -s -o "extension=jpg;jpeg;gif;png,hide-empty-dirs,monitor,cache-dir=/tmp,cache-size=3000,allow_other"
In this example source dir has 1500 Files, max. 3 folder deep structure, (filenames inlcuding spaces and äöü)

Hope this project is not totally abandoned, I couldn't find an alternative and it would be a really cool tool to automatically backup downscaled photos or have my digital photo frame showing only landscape oriented photos.

**Comment by mikeswain** [comment]
Hi, thanks for the input! I had no idea anyone was still using my little project. I'll try and find some time to have a look at this problem - feel free to submit a path yourself though if you work it out.

**Comment by mikeswain** [comment]
Hi I managed to have a look at this at the weekend - a bit embaassed about some of my code in there;-) But it does seem tthe problem may be with readdir_r and re-entrancy It's supposed to be safe but I'm not convinced it is. When you enable hide_empty_dirs, I do a (pretty innefficient;-) recursive check on each sub directory to see if there are no files to be returned. This seems to corrupt the heap. I'm pretty sure my code isn't doing this corruption. Best thing would be a re-implementation that creates a hash of the empty dirs on fuse opendir maybe.

**Comment by allofmex** [comment]
Thank you very much.
Sadly I'm not a c++ programmer, so I cannot help much here.
I tested a bit more too, and it shows that the problem occurres even when hide_empty_dirs is unset, but in this case much less frequent. Hopefully you or someone else can help to rewrite the code.

Another note (I guess not related): I need to mount using "-s" fuse option (singlethreaded). Else I get SegmentationFaults after a while (visible in dmesg).

**Comment by mikeswain** [comment]
I had another look at this as it was puzzling me, and I think I've fixed it. Turned out I was relying on a dodgy way of allocating the directory entry structures, hence overrun. Let me know if this fixes your problem - should run a bit quicker on deep directories too.

**Comment by allofmex** [comment]
Great work! Looks good so far. I'm still testing but seems to work now. Thank you very much.

I have two other things that I would like to contribute (solution available already :-) ). May you sent me a private message to allofmex@gmail.com please? Don't want to publish it here yet. Thanks again.
